# Generated by Django 5.2.8 on 2025-11-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(blank=True, upload_to="employee_photos/"),
        ),
    ]
